services:
  - type: web
    name: pos-backend
    env: docker
    plan: free
    rootDir: ./backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pos-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGINS
        value: "https://high-volume-order-manager-kwi1.vercel.app"
    healthCheckPath: /actuator/health/liveness

databases:
  - name: pos-db
    plan: free
    databaseName: pos_db
    user: pos_user
